### ISSUE TITLE
plugin-worker

### ISSUE THREAD

**Issue by casperlamboo** [systemjs/systemjs#1330]
Currently there is no ideal way to handle web workers. As far as I know there are two ways of using web workers in SystemJS

1. Use WebWorkers to import a javascript file. This javascript file imports system.js and config.js. When both these files are imported SystemJS is used to import the web worker.
2. Create a sfx bundle for the web worker which is loaded.

Both these ways are not ideal. When in production I want to have a single javascript file, this is not the case in both scenarios. Besides that, case 1 is terrible for production because the web worker code has to be transpiled, even if you are in production.

I have thought of an alternate approach. But i'm not sure how to fully implement it (or if it is even possible). It uses [inline web workers](http://www.html5rocks.com/en/tutorials/workers/basics/#toc-inlineworkers). Because of this the sfx bundle is still a single file.

It works as follows. I have created a web worker loader. In the import the path to the worker is given.
```javascript
import Worker from './worker.js!webworker';

// instantiate worker without a path because it is given in the import 
const worker = new Worker();
```
The loader looks as follows.
```javascript
exports.translate = function(load) {
  return [
    'const codeStr = ' + JSON.stringify(load.source) + ';',
    'const blob = new Blob([codeStr]);',
    'const blobURL = self.URL.createObjectURL(blob);',

    'export default function() {',
    '  return new Worker(blobURL);',
    '}'
  ].join('\n');
};
```
When the web worker is imported the code inside the web worker file is stored as string. From said string a blob is created. When calling the exported function a worker with the blob as source is returned.

This works great but the web worker's code won't be transpiled. This is the part where I'm not sure how or if it is even plausible to implement. I was hoping I could use SystemJS to transpile the `load.source` string to a transpiled string. 

(something like this)
```javascript
const codeStr = System.transpileToString(load.source);
```

I have created a [repository](https://github.com/casperlamboo/SystemJS-Web-Workers) if you would like to see a live version of the code.

Issues:
- [x] Creating build for production
- [x] [Getting complete SystemJS config](https://github.com/systemjs/systemjs/issues/1344) (fix  unreleased)
- [x] [Using SystemJS import in Safari](https://github.com/systemjs/systemjs/issues/1353)
- [x] ~~Find a way to load actual worker code sync, so we don't need to queue messages~~ We implemented a system that queues the messages, due to lack of better solution.
- [x] Build without creating files.
- [x] Getting SystemJS file
- [ ] [Use map config to load different loader for production vs dev. ](https://github.com/systemjs/systemjs/issues/1345)
- [ ] [Config defined loader overrules inline defined plugin](https://github.com/systemjs/systemjs/issues/1347)

**Comment by casperlamboo** [comment]
# Update

I've been working on a [worker plugin](https://github.com/casperlamboo/plugin-worker). I've gone with a bit different approach. I use conditional loading to load a different plugin in development and production.

The way importing workers work is the same as in the post above.

```javascript
// load worker using the plugin
import MyWorker from './worker.js!worker';

// instanciate the worker
const myWorker = new MyWorker();
```

## Dev
In development the plugin dynamically creates a worker with something like the following code

```javascript
importScripts('http://localhost:3000/jspm_packages/system.src.js');
System.config({ baseURL: 'http://localhost:3000' })
importScripts('http://localhost:3000/jspm.config.js')

System.import('./worker.js').then(function() {
  self.postMessage('@@@LOADED@@@');
});
```

This code is loaded in the worker as a blob string. When the worker is initialized the worker starts transpiling the given javascript file (in this case `./worker.js`). Because `System.import` loads async all calls made to the worker are queued until the worker is fully loaded. See https://github.com/casperlamboo/plugin-worker/blob/master/plugin-dev.js for full file.

## Production

In production I've gone with an approach similar to the approach I described in the post above. First I create a transpiled string in the fetch function from  `load.adress`. (this doesn't work yet, the plugin uses dummy code as transpiled code). The translate function returns the following string

```javascript
// codeStr contains the transpiled content of the given javascript file, 
// in this case just dummy code, this should be the content of worker.js
const codeStr = "self.addEventListener(\"message\", function(event) {\nself.postMessage(event.data);\n}, false);";
const blob = new Blob([codeStr]);
const blobURL = self.URL.createObjectURL(blob);

export default function() {
  return new Worker(blobURL);
};
```
This creates a blob from the transpiled code. When the worker is initiated it returns a new worker from the blob. See https://github.com/casperlamboo/plugin-worker/blob/master/plugin-production.js for full file.

## Issues

This plugin isn't quite finished; I've encountered a few issues.
 - In the production plugin I've tried to use SystemJS Builder to transpile the worker's code but I receive the following error. This happens on `var Builder = require('systemjs-builder');`  
Error: ```TypeError: Path must be a string. Received undefined```. Perhaps there is a completely different workflow to this that I haven't thought of?
 - In development the worker is created from a blob string. In said blob string I've written these two lines of code ```'importScripts("' + System.baseURL + 'jspm_packages/system.src.js");'``` and ```'importScripts("' + System.baseURL + 'jspm.config.js");'```. Problems is, I'm not sure if I can assume the config and system.js are always in these locations.
- Currently I have to queue the messages because the actual worker code is loaded async, but there is probably no way around this? There is no way to load that given javascript file sync right? 
 - I use conditional mapping to differentiate between the development plugin and production plugin. I'd like to load either the development or the production plugin as entry point, but this doesn't seem to be possible? So I've added a static entry point which mappes the exports from either the production or the development plugin.
 - According to the [jspm 0.17 Beta Guide](http://jspm.io/0.17-beta-guide/conditional-loading.html) I can use `~production` and `production` to differentiate between development and production. But I can't seem to get this to work. I thought the `--minify` in `jspm build index.js dist/app.js --minify` would configure the build to production. Maybe this is only possible from the `jspm.config.js`?

**Comment by guybedford** [comment]
Awesome work. It sounds very similar to the approach taken with the Webpack Worker loader.

The way the build ties between dev and production is exactly the hard part. The reason for this is that the web worker forms its own separate module tree, so we really want that itself to be run through say `builder.buildStatic` (as a separate build to the main bundle / build process going on) in a way that we have a single file that will execute quickly in the worker in production.

Let me know if that makes sense? Perhaps if there is a way to simply hook in and create a parallel static build worker plugin build itself that would help?

> In the production plugin I've tried to use SystemJS Builder to transpile the worker's code but I receive the following error. This happens on var Builder = require('systemjs-builder');
> Error: TypeError: Path must be a string. Received undefined. Perhaps there is a completely different workflow to this that I haven't thought of?

This sounds like it is exactly your trying to hook into the build instance itself? We'd need to expose the configured builder instance already in use for the current build. We can certainly look at an API for this (perhaps even just making it available as `this.builder` within the plugin hooks, which would be done via setting `pluginLoader.builder = this` in https://github.com/systemjs/builder/blob/master/lib/builder.js#L136 if you want to experiment).

> In development the worker is created from a blob string. In said blob string I've written these two lines of code 'importScripts("' + System.baseURL + 'jspm_packages/system.src.js");' and 'importScripts("' + System.baseURL + 'jspm.config.js");'. Problems is, I'm not sure if I can assume the config and system.js are always in these locations.

You can perhaps serialize the configuration from the current loader within the plugin via `this.getConfig()` and then push it in as a single `'System.config(' + JSON.stringify(thisSystem.getConfig()) + ')` call. For the path to SystemJS itself, this can be detected by iterating the scripts in the page and finding the one corresponding to SystemJS. SystemJS has this path internally (scripts can deduce their own paths), so perhaps it is worth exposing that way otherwise.

> Currently I have to queue the messages because the actual worker code is loaded async, but there is probably no way around this? There is no way to load that given javascript file sync right?

The code that imports the worker will only execute after the worker plugin instantiate hook returns. This should be able to fully block on the loading cycle allowing new Worker to be sync? Or am I missing something here?

> I use conditional mapping to differentiate between the development plugin and production plugin. I'd like to load either the development or the production plugin as entry point, but this doesn't seem to be possible? So I've added a static entry point which mappes the exports from either the production or the development plugin.
> According to the jspm 0.17 Beta Guide I can use ~production and production to differentiate between development and production. But I can't seem to get this to work. I thought the --minify in jspm build index.js dist/app.js --minify would configure the build to production. Maybe this is only possible from the jspm.config.js?

This is definitely possible, with the following package.json configuration for the plugin in jspm 0.17:

```javascript
{
  "main": {
    "dev": "./index-dev.js",
    "production": "./index-production.js"
  }
}
```

And environment bulids will build the right branch leaving out the other. Just let me know if you need further help with that.

I have limited time this coming week, but will aim to get back further when I can.

**Comment by guybedford** [comment]
For building, the outFile argument is optional - you can just do:

```javascript
builder.buildStatic(load.address).then(function(output) {
  // output.source, output.sourceMap
});
```

I see what you mean about the async thing. Perhaps instead of `new Worker` an API like `Worker.new().then(function(instance) { ... })` could allow multiple instantiations?

I think we're tracking all the other issues in their places now, but let me know if I've missed any of your questions. This is a really great loader to add to the SystemJS list, please do send a PR to https://github.com/systemjs/systemjs#plugins when it's ready and let me know what else I can do to help get there.

**Comment by casperlamboo** [comment]
> For building, the outFile argument is optional

YES! this was exactly what I needed

> I see what you mean about the async thing. Perhaps instead of new Worker an API like Worker.new().then(function(instance) { ... }) could allow multiple instantiations?

With my API I tried to stay as close to the Worker API as possible. To tackle the async problem, I changed a few things. I added a `WorkerShim` that acts as the Worker API. In development the [WorkerShim](https://github.com/casperlamboo/plugin-worker/blob/master/src/WorkerShim-dev.js) handles all the async stuff and in production the [WorkerShim](https://github.com/casperlamboo/plugin-worker/blob/master/src/WorkerShim-production.js) is just a regular Worker. Using this would look something like this
```javascript
import Worker from 'worker/WorkerShim';
import workerSrc from './worker.js!worker';

// API differs little bit from regular Worker
// path to worker is already given in the import
const worker = new Worker(workerSrc);
worker.postmessage('hello world');
```
I think this is the most elegant solution, as it stays very similar to the `Worker`'s API. This also keeps the user's code module/build system agnostic. The downside is that, during development, it requires a shim that doesn't handle all edge cases perfectly.  What do you think?

**Comment by guybedford** [comment]
Yeah that certainly makes sense. Do you really need to still pass the
source? Perhaps make the constructor take no arguments if it is already
bound?

I'm still not sure I fully follow why you wouldn't block on at least
fetching the worker source though for the development version.

**Comment by casperlamboo** [comment]
> Yeah that certainly makes sense. Do you really need to still pass the
source? Perhaps make the constructor take no arguments if it is already
bound?

> I'm still not sure I fully follow why you wouldn't block on at least
fetching the worker source though for the development version.

I don't completely follow, can you perhaps elaborate a little more? Maybe give a little example on how you would like to use the plugin?

**Comment by guybedford** [comment]
@casperlamboo sorry I'll try not to rush out these responses - I seem to have misread your example code. It seems like you are just using `new Worker()` in the example above which was the first point.

The main thing is the blocking behaviour then. It's worth noting here that web workers will support `importScripts` to es modules in future, and what this will look like - that will effectively provide the sync System.import behaviour you're asking about. The way you've handled this by buffering the worker methods does then exactly replicate the future behaviour.

So I do think you've cracked the problem exactly right, and the code looks really nice as well btw!

**Comment by guybedford** [comment]
The module workers reference is here - https://html.spec.whatwg.org/multipage/workers.html#module-worker-example.

It seems like it will be:

```javascript
new Worker("worker.js", { type: "module" });
```

where `importScripts` will not be supported, instead to use es modules.

So we're effectively providing that through the plugin which is great. Perhaps we should stop `importScripts` from being supported too.

**Comment by casperlamboo** [comment]
Ah okay, thats great! So we'll keep my current implementation of loading the worker via the `workerShim`?

Apart from two issues (both are handled in their own issue: #1347 and #1345) there is still one untackled issue. Currently `system.js` is imported in the following way
```javascript
importScripts(System.baseURL + 'jspm_packages/system.src.js');
```
https://github.com/casperlamboo/plugin-worker/blob/master/src/loader-dev.js#L7
So it isn't flexible when people have their jspm_packages configured in a different way. You suggested I'd loop through all existing script tags trying to find the SystemJS' script

>For the path to SystemJS itself, this can be detected by iterating the scripts in the page and finding the one corresponding to SystemJS. 

Or expose said path in SystemJS itself

>SystemJS has this path internally (scripts can deduce their own paths), so perhaps it is worth exposing that way otherwise.

It would be very useful to have access to this path, maybe through a property or getter of SystemJS.
If I'm correct this [line](https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L1572) creates the link to the path. In fact the variable `$__curScript` is already globally defined, but that's probably internal and subject to change?

**Comment by guybedford** [comment]
> Ah okay, thats great! So we'll keep my current implementation of loading the worker via the workerShim?

Yes exactly.

I'd be happy to take a PR to expose the path to SystemJS as `SystemJS.scriptSrc` or something similar. Note that it may be undefined in certain environments (eg <script async> in old browsers), so it would still be necessary to have a fallback I think.

**Comment by guybedford** [comment]
Is there anything left here still to track?

**Comment by casperlamboo** [comment]
No, every thing is tracked in their own issues. Closing this issue now. I was waiting for the next release of System JS before composing a PR to add the plugin to the plugin list.
