### ISSUE TITLE
Port Tracking

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#414]
The following commits need to be ported up to the 0.17 branch:

* https://github.com/systemjs/systemjs/commit/de1f7ee999cacb6866fff91291fac4d062109c91
* https://github.com/systemjs/systemjs/commit/8d8c06518fb4425542e81ba87e4caa83498170b0
* https://github.com/systemjs/systemjs/commit/5806665b374c096e61cac533709981d0eac39cbb
* https://github.com/systemjs/systemjs/commit/b279fd755b873cd11ae82315ee3608a66f3485e6

**Comment by crisptrutski** [comment]
Thanks - lets keep this issue running to track these. We can strikethrough SHAs as they teleport.

**Comment by szepeviktor** [comment]
Or use a task list.

- [ ] https://github.com/systemjs/systemjs/commit/de1f7ee999cacb6866fff91291fac4d062109c91
- [ ] https://github.com/systemjs/systemjs/commit/8d8c06518fb4425542e81ba87e4caa83498170b0
- [ ] https://github.com/systemjs/systemjs/commit/5806665b374c096e61cac533709981d0eac39cbb
- [ ] https://github.com/systemjs/systemjs/commit/b279fd755b873cd11ae82315ee3608a66f3485e6

**Comment by guybedford** [comment]
These are all ported now.
